import { Toaster } from '@/components/ui/sonner';
import { quicksand } from '@/configs/fonts';
import AppProvider from '@/provider/AppProvider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <AppProvider>{children}</AppProvider>
      </body>
      <Toaster position="top-center" richColors duration={2000} style={{ ...quicksand.style }} />
    </html>
  );
}
