import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';

const recursive = Recursive({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>{children}</body>
      <Toaster position="top-right" richColors duration={2000} style={{ ...recursive.style }} />
    </html>
  );
}
